
platform :ios, '9.0'

target 'Pet-Community-Prototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pet-Community-Prototype
  pod 'lottie-ios'

end
